# ┌────────────────────────────────
# │ Настройки самого удобного способа аутентификации - через вход с лицензионного аккаунта.
# │ 
# │ Из-за технических ограничений, заложенных Mojang в клиент игры, нельзя узнать, входит игрок с лицензии или нет.
# │ Когда игрок подключается к серверу, мы можем послать один из двух пакетов:
# │ — Требование Mojang аккаунта (если клиент пиратский, он САМ кикнется от такого пакета)
# │ — Одобрение входа (сразу пустит любой клиент, пиратский или лицензионный)
# │ Из-за этого ограничения невозможно убрать регистрацию для лицензионных игроков, потому что мы никак не можем
# │ узнать, с лицензии ли они зашли.
# │ 
# │ Некоторые плагины решают это довольно спорным методом: требуют лицензию для всех лицензионных ников.
# │ Я считаю, что это глупая затея: большинство игроков - пираты, и они часто используют лицензионные ники (для скина или просто случайно).
# │ 
# │ В качестве решения, я предлагаю такую схему:
# │ 1. Все игроки проходят регистрацию, всегда.
# │ 2. После регистрации игрок может ввести /license, которая объяснит ему, что делать.
# │ 3. При следующем входе у игрока потребуют Mojang аккаунт (тот самый кикающий пакет):
# │ ——— Если игрок сам кикнется, значит, он вошёл с пиратки - процесс отменён, он вновь пират.
# │ ——— Если игрок успешно войдёт, плагин запомнит его как владельца лицензии, и будет всегда приветствовать тем пакетом.
# │ Таким образом игроки с лицензией могут за 30 секунд навсегда отказаться от пароля и 2FA.
# │ Уведомления от привязок всё ещё будут приходить, привязки останутся для контроля аккаунта, просто без 2FA.
# │ 
# │ Введя эту команду повторно, игрок может отключить режим лицензии - следующий вход уже будет, как у всех пиратов.
# │ 
# │ Почему это называется "премиум", а не "лицензия"?
# │ В СНГ из-за повсеместного пиратства прижилось такое название, поэтому я использую его для упрощения понимания.
# └────────────────────────────────
enabled: true

# Человеческое название этого способа, чтобы в редких случаях показать игрокам.
display-name: 'лицензию'

# ┌────────────────────────────────
# │ Настройки команды для переключения премиум-режима.
# └────────────────────────────────
command:
  aliases:
  - 'premium'
  cooldown: '700 мсек'

# ┌────────────────────────────────
# │ Настройки процесса включения премиум-режима.
# └────────────────────────────────
enabling:
  warning: |-
    <color:#ff8d0a>╔</color>
    <color:#ff8d0a>╠</color>        <u>Переключение в режим <b><color:#ff8d0a>ЛИЦЕНЗИИ</color></b></u>
    <color:#ff8d0a>╠</color>
    <color:#ff8d0a>╠</color> 1. Вы больше не сможете заходить с пиратки
    <color:#ff8d0a>╠</color> 2. Это полностью избавит вас от паролей и 2FA
    <color:#ff8d0a>╠</color> 3. Вы сможете вернуться к пиратке, введя <u><color:#ff8d0a>/premium</color></u>
    <color:#ff8d0a>╠</color>
    <color:#ff8d0a>╠</color>  Нажмите <color:#ff8d0a><click:run_command:'<callback>'>СЮДА</click></color>, чтобы продолжить.
    <color:#ff8d0a>╚</color>
  start: |-
    <color:#ff8d0a>╔</color>
    <color:#ff8d0a>╠</color>        <u>Переключение в режим <b><color:#ff8d0a>ЛИЦЕНЗИИ</color></b></u>
    <color:#ff8d0a>╠</color>
    <color:#ff8d0a>╠</color> Процесс начат.
    <color:#ff8d0a>╠</color> Перезайдите на сервер и осуществите логин.
    <color:#ff8d0a>╠</color>
    <color:#ff8d0a>╠</color> При входе с пиратки, вас кикнет,
    <color:#ff8d0a>╠</color> но после начнёт впускать - процесс будет отменён.
    <color:#ff8d0a>╠</color>
    <color:#ff8d0a>╚</color>
  success: |-
    <color:#ff8d0a>╔</color>
    <color:#ff8d0a>╠</color> <b>Вы переключились в режим <color:#ff8d0a>ЛИЦЕНЗИИ</color>!
    <color:#ff8d0a>╚</color>

# ┌────────────────────────────────
# │ Настройки процесса выключения премиум-режима.
# └────────────────────────────────
disabling:
  warning: |-
    <color:#ff8d0a>╔</color>
    <color:#ff8d0a>╠</color>        <u>Переключение в режим <b><color:#ff8d0a>ПИРАТА</color></b></u>
    <color:#ff8d0a>╠</color>
    <color:#ff8d0a>╠</color> 1. Вы сможете входить как с пиратки, так и с лицензии
    <color:#ff8d0a>╠</color> 2. У вас снова появятся пароли, 2FA и прочие проверки
    <color:#ff8d0a>╠</color> 3. Вы сможете вернуться к лицензии, введя <u><color:#ff8d0a>/premium</color></u>
    <color:#ff8d0a>╠</color>
    <color:#ff8d0a>╠</color>  Нажмите <color:#ff8d0a><click:run_command:<callback>'>СЮДА</click></color>, чтобы продолжить.
    <color:#ff8d0a>╚</color>
  success: |-
    <color:#ff8d0a>╔</color>
    <color:#ff8d0a>╠</color> <b>Вы переключились в режим <color:#ff8d0a>ПИРАТА</color>!
    <color:#ff8d0a>╚</color>

# ┌────────────────────────────────
# │ Настройки процесса входа игрока.
# └────────────────────────────────
login:
  message:
    enabled: false
    content: '<green>Вы вошли с лицензии, аутентификация не требуется.'
  title:
    enabled: true
    title: '<green>С возвращением!'
    subtitle: '<green>Вы вошли с лицензии!'
    duration-fade-in: '500 мсек'
    duration-stay: '3 сек 500 мсек'
    duration-fade-out: '1 сек'
