# ┌────────────────────────────────
# │ Команда /link [сервис].
# │ Она позволяет игроку привязать свой аккаунт к какому-то из включённых сервисов (VK, Telegram, Discord и т.д.).
# │ Если у вас не включены никакие сервисы, команда автоматически исчезнет.
# └────────────────────────────────
aliases:
- 'link'
cooldown: '700 мсек'
permissions: []
arguments:
  service: 'сервис'
  code: 'код'
messages:
  available-services: |-
    <yellow>Доступные сервисы: <white><services></white></yellow>
    <yellow>Введите <white>/link [сервис]</white> для привязки.</yellow>
  unknown-code: '<red>Неизвестный код. Может, вы хотели отправить его боту, а не сюда?'
  unknown-service: '<red>Неизвестный сервис ''<input>''. Доступны: <white><services></white>.'
  already-linked: '<red>Вы уже привязаны к сервису <service>!'
