# ┌────────────────────────────────
# │ Настройки, касающиеся паролей.
# │ Как правило, стандартные настройки всем подходят.
# └────────────────────────────────


# Настройки поведения при вводе игроком неправильного пароля.
incorrect-password:
  message:
    enabled: false
    content: '<b><color:#d40808>[X]</color></b>Неправильный пароль! Осталось попыток:
      <permits> (<used>/<max>)'
  title:
    enabled: true
    title: '<color:#d40808>Неправильный пароль'
    subtitle: '<color:#e62929>Осталось попыток: <permits> (<used>/<max>)'
    duration-fade-in: '500 мсек'
    duration-stay: '5 сек'
    duration-fade-out: '1 сек'
  anti-brute-force:
    enabled: true
    permits: 5
    kicks-before-ban: 3
    ban-duration: '5 мин'
    kick-reason: |-
      <color:#d40808>У вас кончились попытки ввода пароля.
      Попробуйте ещё раз позже.
    ban-reason: |-
      <color:#e62929>Вы слишком часто вводили неправильный пароль.
      Вы сможете снова войти на сервер через <duration>

# ┌────────────────────────────────
# │ Определяет минимальную и максимальную длину пароля.
# │ Не стоит позволять игрокам ставить короткие пароли - их легко подобрать.
# └────────────────────────────────
length:
  minimum: 4
  maximum: 100
  message:
    enabled: false
    content: '<bold><red>Пароль слишком короткий!</bold> <gray>(минимум <u>4 символа</u>).'
  title:
    enabled: true
    title: '<color:#d40808>Пароль слишком короткий!'
    subtitle: '<color:#e62929>Используйте хотя бы <u>4 символа</u>'
    duration-fade-in: '500 мсек'
    duration-stay: '5 сек'
    duration-fade-out: '1 сек'

# ┌────────────────────────────────
# │ Запрещает использовать свой ник в качестве пароля.
# │ Да, многие игроки так делают... Это очень странно.
# └────────────────────────────────
player-name:
  enabled: true
  message:
    enabled: false
    content: '<bold><red>Нельзя делать паролем <u>собственный ник</u>.'
  title:
    enabled: true
    title: '<color:#d40808>Небезопасный пароль!'
    subtitle: '<color:#e62929>Нельзя делать паролем <u>собственный ник</u>'
    duration-fade-in: '500 мсек'
    duration-stay: '5 сек'
    duration-fade-out: '1 сек'

# ┌────────────────────────────────
# │ Запрещает использовать пароли, состоящие только из цифр.
# │ Такие пароли легче подобрать, но игроки могут предпочитать их использовать.
# └────────────────────────────────
only-digits:
  enabled: false
  message:
    enabled: false
    content: '<bold><red>Пароль не должен состоять <u>только из цифр</u>.'
  title:
    enabled: true
    title: '<color:#d40808>Небезопасный пароль!'
    subtitle: '<color:#e62929>Пароль не должен состоять <u>только из цифр</u>'
    duration-fade-in: '500 мсек'
    duration-stay: '5 сек'
    duration-fade-out: '1 сек'

# ┌────────────────────────────────
# │ Требует наличие хотя бы <количество> цифр в пароле.
# │ Пароли с числами сложнее подобрать, но не все игроки хотят использовать их.
# └────────────────────────────────
without-digits:
  at-least: 0
  message:
    enabled: false
    content: '<bold><red>Пароль должен содержать хотя бы <u>одну цифру</u>.'
  title:
    enabled: true
    title: '<color:#d40808>Небезопасный пароль!'
    subtitle: '<color:#e62929>Используйте хотя бы одну <u>цифру</u>'
    duration-fade-in: '500 мсек'
    duration-stay: '5 сек'
    duration-fade-out: '1 сек'

# ┌────────────────────────────────
# │ Проверяет пароль через систему https://haveibeenpwned.com/Passwords
# │ Хотя сливы именно Minecraft сетей вряд ли попадают туда,
# │ такая проверка хорошо защищает от паролей, которые часто появляются в словарях для подбора.
# │ 
# │ Эта проверка не допускает слива ваших паролей - сайт получает лишь кусочек хеша пароля.
# └────────────────────────────────
have-i-been-pwned:
  enabled: true
  threshold: 100000
  # Расходует примерно (64 + 4 + 4 + 2 * длина) байт ОЗУ за каждый закешированный пароль. 10000 = ~1 MB.
  max-cache-size: 50000
  message:
    enabled: false
    content: '<bold><red>Этот пароль слишком популярный.'
  title:
    enabled: true
    title: '<color:#d40808>Небезопасный пароль!'
    subtitle: '<color:#e62929>Этот пароль <u>слишком популярный</u>'
    duration-fade-in: '500 мсек'
    duration-stay: '5 сек'
    duration-fade-out: '1 сек'

# ┌────────────────────────────────
# │ Настройки хеширования (bcrypt + хеши из других плагинов).
# │ Стандартные настройки оптимальны.
# └────────────────────────────────
hashing:
  max-threads: -1
  cost: 14
  benchmark:
    enabled: true
    target: '1 сек 500 мсек'
    range: '12..31'
